src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $reservation_id = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Guest $guest_id = null;

    #[ORM\ManyToMany(targetEntity: Room::class, inversedBy: 'reservations')]
    private Collection $room_id;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $check_in_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $check_out_date = null;

    #[ORM\Column(nullable: true)]
    private ?float $total_price = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[ORM\ManyToOne(inversedBy: 'reseration_id')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Payment $payment = null;

    public function __construct()
    {
        $this->room_id = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReservationId(): ?string
    {
        return $this->reservation_id;
    }

    public function setReservationId(string $reservation_id): static
    {
        $this->reservation_id = $reservation_id;

        return $this;
    }

    public function getGuestId(): ?guest
    {
        return $this->guest_id;
    }

    public function setGuestId(?guest $guest_id): static
    {
        $this->guest_id = $guest_id;

        return $this;
    }

    /**
     * @return Collection<int, room>
     */
    public function getRoomId(): Collection
    {
        return $this->room_id;
    }

    public function addRoomId(room $roomId): static
    {
        if (!$this->room_id->contains($roomId)) {
            $this->room_id->add($roomId);
        }

        return $this;
    }

    public function removeRoomId(room $roomId): static
    {
        $this->room_id->removeElement($roomId);

        return $this;
    }

    public function getCheckInDate(): ?\DateTimeInterface
    {
        return $this->check_in_date;
    }

    public function setCheckInDate(\DateTimeInterface $check_in_date): static
    {
        $this->check_in_date = $check_in_date;

        return $this;
    }

    public function getCheckOutDate(): ?\DateTimeInterface
    {
        return $this->check_out_date;
    }

    public function setCheckOutDate(\DateTimeInterface $check_out_date): static
    {
        $this->check_out_date = $check_out_date;

        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->total_price;
    }

    public function setTotalPrice(?float $total_price): static
    {
        $this->total_price = $total_price;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getPayment(): ?Payment
    {
        return $this->payment;
    }

    public function setPayment(?Payment $payment): static
    {
        $this->payment = $payment;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('reservation_id')
            ->add('check_in_date')
            ->add('check_out_date')
            ->add('total_price')
            ->add('status')
            ->add('guest_id')
            ->add('room_id')
            ->add('payment')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/reservation')]
class ReservationController extends AbstractController
{
    #[Route('/', name: 'app_reservation_index', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_reservation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reservation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation index{% endblock %}

{% block body %}
    <h1>Reservation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Reservation_id</th>
                <th>Check_in_date</th>
                <th>Check_out_date</th>
                <th>Total_price</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.reservationId }}</td>
                <td>{{ reservation.checkInDate ? reservation.checkInDate|date('Y-m-d') : '' }}</td>
                <td>{{ reservation.checkOutDate ? reservation.checkOutDate|date('Y-m-d') : '' }}</td>
                <td>{{ reservation.totalPrice }}</td>
                <td>{{ reservation.status }}</td>
                <td>
                    <a href="{{ path('app_reservation_show', {'id': reservation.id}) }}">show</a>
                    <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_reservation_new') }}">Create new</a>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>
{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Reservation_id</th>
                <td>{{ reservation.reservationId }}</td>
            </tr>
            <tr>
                <th>Check_in_date</th>
                <td>{{ reservation.checkInDate ? reservation.checkInDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Check_out_date</th>
                <td>{{ reservation.checkOutDate ? reservation.checkOutDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Total_price</th>
                <td>{{ reservation.totalPrice }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ reservation.status }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}