src/Entity/Payment.php
<?php

namespace App\Entity;

use App\Repository\PaymentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PaymentRepository::class)]
class Payment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $payment_id = null;

    #[ORM\OneToMany(mappedBy: 'payment', targetEntity: Reservation::class)]
    private Collection $reseration_id;

    #[ORM\Column]
    private ?float $amount = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $payment_date = null;

    #[ORM\Column(length: 255)]
    private ?string $payment_method = null;

    public function __construct()
    {
        $this->reseration_id = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPaymentId(): ?string
    {
        return $this->payment_id;
    }

    public function setPaymentId(string $payment_id): static
    {
        $this->payment_id = $payment_id;

        return $this;
    }

    /**
     * @return Collection<int, reservation>
     */
    public function getReserationId(): Collection
    {
        return $this->reseration_id;
    }

    public function addReserationId(reservation $reserationId): static
    {
        if (!$this->reseration_id->contains($reserationId)) {
            $this->reseration_id->add($reserationId);
            $reserationId->setPayment($this);
        }

        return $this;
    }

    public function removeReserationId(reservation $reserationId): static
    {
        if ($this->reseration_id->removeElement($reserationId)) {
            // set the owning side to null (unless already changed)
            if ($reserationId->getPayment() === $this) {
                $reserationId->setPayment(null);
            }
        }

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getPaymentDate(): ?\DateTimeInterface
    {
        return $this->payment_date;
    }

    public function setPaymentDate(\DateTimeInterface $payment_date): static
    {
        $this->payment_date = $payment_date;

        return $this;
    }

    public function getPaymentMethod(): ?string
    {
        return $this->payment_method;
    }

    public function setPaymentMethod(string $payment_method): static
    {
        $this->payment_method = $payment_method;

        return $this;
    }
}

src/Form/PaymentType.php
<?php

namespace App\Form;

use App\Entity\Payment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PaymentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('payment_id')
            ->add('amount')
            ->add('payment_date')
            ->add('payment_method')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Payment::class,
        ]);
    }
}

src/Controller/PaymentController.php
<?php

namespace App\Controller;

use App\Entity\Payment;
use App\Form\PaymentType;
use App\Repository\PaymentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/payment')]
class PaymentController extends AbstractController
{
    #[Route('/', name: 'app_payment_index', methods: ['GET'])]
    public function index(PaymentRepository $paymentRepository): Response
    {
        return $this->render('payment/index.html.twig', [
            'payments' => $paymentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_payment_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $payment = new Payment();
        $form = $this->createForm(PaymentType::class, $payment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($payment);
            $entityManager->flush();

            return $this->redirectToRoute('app_payment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('payment/new.html.twig', [
            'payment' => $payment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_payment_show', methods: ['GET'])]
    public function show(Payment $payment): Response
    {
        return $this->render('payment/show.html.twig', [
            'payment' => $payment,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_payment_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Payment $payment, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PaymentType::class, $payment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_payment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('payment/edit.html.twig', [
            'payment' => $payment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_payment_delete', methods: ['POST'])]
    public function delete(Request $request, Payment $payment, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$payment->getId(), $request->request->get('_token'))) {
            $entityManager->remove($payment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_payment_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/payment/_delete_form.html.twig
<form method="post" action="{{ path('app_payment_delete', {'id': payment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ payment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/payment/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/payment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Payment{% endblock %}

{% block body %}
    <h1>Edit Payment</h1>

    {{ include('payment/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_payment_index') }}">back to list</a>

    {{ include('payment/_delete_form.html.twig') }}
{% endblock %}

templates/payment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Payment index{% endblock %}

{% block body %}
    <h1>Payment index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Payment_id</th>
                <th>Amount</th>
                <th>Payment_date</th>
                <th>Payment_method</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for payment in payments %}
            <tr>
                <td>{{ payment.id }}</td>
                <td>{{ payment.paymentId }}</td>
                <td>{{ payment.amount }}</td>
                <td>{{ payment.paymentDate ? payment.paymentDate|date('Y-m-d') : '' }}</td>
                <td>{{ payment.paymentMethod }}</td>
                <td>
                    <a href="{{ path('app_payment_show', {'id': payment.id}) }}">show</a>
                    <a href="{{ path('app_payment_edit', {'id': payment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_payment_new') }}">Create new</a>
{% endblock %}

templates/payment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Payment{% endblock %}

{% block body %}
    <h1>Create new Payment</h1>

    {{ include('payment/_form.html.twig') }}

    <a href="{{ path('app_payment_index') }}">back to list</a>
{% endblock %}

templates/payment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Payment{% endblock %}

{% block body %}
    <h1>Payment</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ payment.id }}</td>
            </tr>
            <tr>
                <th>Payment_id</th>
                <td>{{ payment.paymentId }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ payment.amount }}</td>
            </tr>
            <tr>
                <th>Payment_date</th>
                <td>{{ payment.paymentDate ? payment.paymentDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Payment_method</th>
                <td>{{ payment.paymentMethod }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_payment_index') }}">back to list</a>

    <a href="{{ path('app_payment_edit', {'id': payment.id}) }}">edit</a>

    {{ include('payment/_delete_form.html.twig') }}
{% endblock %}